# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AMRAdapterStorylyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'AMRSDK', '~> 1.4'
	pod 'AMRAdapterAdmost', '~> 1.3'
	pod 'Storyly', '~> 1.5.0'
end
